import type { Metadata } from "next";
import "@/styles/globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";
import Header from "@/components/Header";
import { getUser } from "@/auth/server";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// wrapper for all pages in the app; suppressHydrationWarning is used to prevent hydration errors
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col min-h-screen w-full bg-slate-800 dark:bg-slate-900 text-slate-200 dark:text-slate-200">
            <Header user={user && user.email ? { email: user.email } : null} />
            <main className="flex flex-1 flex-col justify-between px-4 pt-10 xl:px-8 caret-red-900">
              {children}
            </main>
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
