"use client";
// import type { Metadata } from "next";
import Header from "@/components/Header";
import "@/styles/globals.css";
import { useState, useEffect } from 'react';
import { Session } from '@supabase/auth-helpers-nextjs';
import { ThemeProvider } from "@/providers/ThemeProvider";
// import PageTwo from "@/components/PageTwo";

import { Toaster } from "@/components/ui/toaster";
import NoteProvider from "@/providers/NoteProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { getSession } from "@/auth/server";
// import { AppSidebar } from "@/components/x";
// import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
// import { cookies } from 'next/headers'

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// wrapper for all pages in the app; suppressHydrationWarning is used to prevent hydration errors
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [session, setSession] = useState<Session | null>(null);

  useEffect(() => {
    const fetchSession = async () => {
      const sessionData = await getSession();
      setSession(sessionData);
    };
    fetchSession();
  }, []);

  if (!session) {
    console.log('session', session);
  }

  // const cookieStore = cookies()
  // const supabase = await createClient(cookieStore);
  // const { data: { user } } = await supabase.auth.getUser()
  // const user = await getUser();
  // console.log('user', user);

  // const supabase = createServerComponentClient({ cookies })
  // const { data: { user }, error: authError } = await supabase.auth.getUser()
  // if (authError) { console.log('session', authError); }

  // const session = await getSession();
  const user = session?.user;
  if (!user) { console.log('user', user); }

  // {/* <Head> */}
  {/* <title>HTMX CRUD with Supabase</title> */ }
  {/* <Script src="" strategy="afterInteractive" /> either async or this way*/ }
  {/* <script src="https://unpkg.com/htmx.org@1.6.1" async></script> */ }
  {/* </Head> */ }
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NoteProvider>
            <SidebarProvider>
              {/* <AppSidebar /> */}
              <div className="flex flex-col min-h-screen w-full bg-slate-800 dark:bg-slate-900 text-slate-200 dark:text-slate-200">
                {session && <Header session={session} />}
                <main className="flex flex-1 flex-col justify-between px-4 pt-10 xl:px-8 caret-red-900">
                  {children}
                </main>
                {/* <PageTwo session={session} /> */}
              </div>
            </SidebarProvider>
            <Toaster />
          </NoteProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
